#!/usr/bin/env python3

import os
import sys
from pathlib import Path
from typing import Dict, List

from ruamel import yaml
from jinja2 import Template

EXTENSIONS = [
    '.liquid',  # for backwards compatibility
    '.j2'
]

# where the template files can be read + written
files_path = Path(sys.argv[1])

yaml_file_paths = sys.argv[2:]


def load_config(files: List) -> Dict:
    config = {}

    for file in files:
        with open(file) as stream:
            config.update(yaml.safe_load(stream) or {})

    return config


def iterate_templates(root_path: Path, values: Dict):
    for root, dirs, files in os.walk(root_path):
        for file_path in files:
            template_file = Path(root, file_path)

            for extension in EXTENSIONS:
                if template_file.name.endswith(extension):
                    out_file = Path(root, template_file.name[:-len(extension)])

                    template = Template(template_file.read_text())
                    out_file.write_text(template.render(values))

                    break


if __name__ == '__main__':
    config = load_config(yaml_file_paths)
    iterate_templates(files_path, config)
