#!/usr/bin/env python3

import subprocess
import sys

from ruamel import yaml

file = sys.argv[1]

with open(file) as stream:
    try:
        content = yaml.safe_load(stream) or dict()

        result = {}

        for key in content:
            secret_path = str(content[key])
            outcome = subprocess.run(['gopass', 'show', '-o', secret_path], stdout=subprocess.PIPE)

            if outcome.returncode != 0:
                sys.exit(2)
            else:
                result[key] = outcome.stdout.decode('utf-8')

        if result:
            yaml2 = yaml.YAML()
            yaml2.dump(result, sys.stdout)
    except yaml.YAMLError as exc:
        print(exc)
        sys.exit(1)
