#!/usr/bin/expect -f
#
# This script wraps the `ssh` command in an `expect` script,
# to automatically enter sudo passwords for the user.
#

set sudo_pass "$env(SUDO_PASS)";

set timeout -1

spawn -noecho {*}$argv
#expect -exact "Password: "
expect -exact "\[sudo\] password for "
send -- "$sudo_pass\r"
interact

lassign [wait] pid spawnid os_error_flag value

if {$os_error_flag == 0} {
  puts "exit status: $value"
} else {
  puts "errno: $value"
}
exit $value
