#!/bin/bash
#
# welder-run-script
#
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

playbook="$1"
script="$2"

[ -z "$playbook" ]       && __fail "Usage: x run-script <playbook-name>"
[ ! -f ./$playbook.yml ] && __fail "No ${playbook}.yml file found"

__load_config "$playbook.yml"

ssh -t "$W_SSH_URL" -p "$W_SSH_PORT" "$(< $script)"

__success "done!"
