#!/bin/bash
#
# Removes compiled files from the server
#
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

. $WELDER_ROOT/libexec/priv/_helpers

playbook="$1"
[ -z "$playbook" ] && __fail "Usage: x cleanup <playbook-name>"

__load_config "$playbook.yml"

ssh "$W_SSH_URL" -p "$W_SSH_PORT" "rm -rf .welder/"

__success "data directory removed from ${W_SSH_URL}"
